### ISSUE TITLE
renderPixelBuffer 输出的数据只有一二帧

### ISSUE THREAD

**Issue by HushengGen** [Faceunity/FULiveDemo#1]
- (FUOutput)renderPixelBuffer:(CVPixelBufferRef)pixelBuffer bgraTexture:(GLuint)textureHandle withFrameId:(int)frameid items:(int *)items itemCount:(int)itemCount;
请教下，这个接口pixelBuffer和textureHandle是什么关系，可以只传textureHandle，pixelBuffer为NULL吗？ 目前调用这个接口返回一两帧数据后就一直返回这一两帧数据，请问什么情况下可能出现这种情况？谢谢

**Comment by jdbbjd** [comment]
pixelBuffer是用来做人脸识别的，如果不传pixelBuffer，那这个接口就不会生效。你说的问题是这个接口内部改变了FBO，现在我们已经再内部做了设回原来的的FBO操作，修复了该问题。
