### ISSUE TITLE
pod 安装不上 报错

### ISSUE THREAD

**Issue by Verchen** [Faceunity/FULiveDemo#12]
<img width="729" alt="wx20180822-145228 2x" src="https://user-images.githubusercontent.com/14816675/44447520-07ccf300-a61b-11e8-9cad-46d16935929d.png">

**Comment by Verchen** [comment]
@jdbbjd

**Comment by OneWang** [comment]
遇到同样的问题，麻烦开发人员抓紧时间处理一下！

**Comment by Verchen** [comment]
@OneWang 我的解决了，把pod的源换成这个https://gems.ruby-china.org，注意最后边是不带/的

**Comment by OneWang** [comment]
我的源就是这个啊；还是不行；

**Comment by anhaoxiong** [comment]
你们的 SDK pod 更新很慢，可以优化一下，将 SDK 放到某个地方存起来，podspec 中修改一下下载地址，更新速度杠杠的

**Comment by jdbbjd** [comment]
多谢您的建议，后续我们会对下载做优化
