### ISSUE TITLE
崩溃，每次都崩在初始化的地方

### ISSUE THREAD

**Issue by qvcheng** [Faceunity/FULiveDemo#14]
<img width="727" alt="default" src="https://user-images.githubusercontent.com/14816675/45337741-2ab84a80-b5bc-11e8-9849-935e6f8d6e8a.png">

**Comment by Verchen** [comment]
@jdbbjd

**Comment by jdbbjd** [comment]
有可能是证书不对，麻烦贴一下崩溃的log

**Comment by kurtchen1988** [comment]
no response
