### ISSUE TITLE
项目pod update使用master分支出错

### ISSUE THREAD

**Issue by usattc** [Faceunity/FULiveDemo#15]
你好, 
在项目中pod使用'Nama-lite', update报错:
This repository is over its data quota. Purchase more data packs to restore access.

指定'Nama-lite'为5.5.0后正常, 请问master的5.3.0是否有问题?

**Comment by kurtchen1988** [comment]
之前的pod数据被清理掉了，建议使用新版本的SDK，谢谢您的反馈
