### ISSUE TITLE
在7p下我正常打开采集预览，并且设置美颜。这时候我打开手机拍照，切换前置摄像头，然后拍照完毕退出系统拍照，这个时候美颜没有效果。这种情况只有7p会有问题，其它手机没有问题。

### ISSUE THREAD

**Issue by NorthDogLi** [Faceunity/FULiveDemo#16]
流程：
1.采集视频数据，然后通过openGL预览，并且设置美颜，
2.点击按钮，打开系统拍照，这个时候关闭我们自己的视频采集
3.调起系统拍照后，切换为前置摄像头，点击拍照，完成拍照
4.回调系统拍照，重新打开我们的视频采集，预览，设置美颜，发现美颜没有效果了。

这种情况下只有7p手机有问题，其他手机没有问题。

**Comment by jadecheng17** [comment]
> 流程：
> 1.采集视频数据，然后通过openGL预览，并且设置美颜，
> 2.点击按钮，打开系统拍照，这个时候关闭我们自己的视频采集
> 3.调起系统拍照后，切换为前置摄像头，点击拍照，完成拍照
> 4.回调系统拍照，重新打开我们的视频采集，预览，设置美颜，发现美颜没有效果了。
> 
> 这种情况下只有7p手机有问题，其他手机没有问题。

您好，非常感谢您的反馈，麻烦问下运行我们的demo有问题吗，最好可以提供下录制视频。IOS中只有7P是出现问题的？

**Comment by NorthDogLi** [comment]
你好，这个问题是由于我们其它原因造成的，可以关闭这个问题了。

**Comment by kurtchen1988** [comment]
not an issue
