### ISSUE TITLE
demo性能问题

### ISSUE THREAD

**Issue by dengfeng520** [Faceunity/FULiveDemo#17]
在`5C`上，视频帧率每秒18帧:,iOS 系统版本9.0,没有开滤镜之前，CPU使用率11%左右，一开滤镜瞬间飙到50%了，而且掉帧卡顿严重。
`5S`上视频18帧，iOS 12，掉帧情况稍好一点。
在8P和XS上，视频帧率每秒24帧，没开滤镜`CPU`使用率27%左右，开了滤镜`CPU`使用率飙到60%了。。。

**Comment by chenzk15266** [comment]
@dengfeng520 请问你用的是master分支下的demo吗？master分支下demo里面的SDK版本还是较老的版本，即v5.3.0，目前最新的SDK已经到v5.9.0了，最新版本的demo应该在dev分支clone，烦请该demo再验证一下。

**Comment by dengfeng520** [comment]
感谢回复，是`master`分支下的代码，我切换分支代码再试一下。

**Comment by kurtchen1988** [comment]
现已对性能进行优化，可尝试最新版demo。谢谢您的反馈
