### ISSUE TITLE
FUAPIDemoBar not support X86_64

### ISSUE THREAD

**Issue by buaayoung** [Faceunity/FULiveDemo#3]

**Comment by buaayoung** [comment]
你好，能给我一个支持x86_64架构的FUAPIDemoBar.framework吗，项目因为引入了它不能在模拟器上运行，谢谢！

**Comment by jdbbjd** [comment]
你好，如果你是我们的客户，可以联系我们的技术支持获取。

**Comment by jdbbjd** [comment]
你好，如果你是我们的客户，可以联系我们的技术支持获取。
