### ISSUE TITLE
一个关键函数的 Swift 兼容问题

### ISSUE THREAD

**Issue by iTofu** [Faceunity/FULiveDemo#4]
```objc
- (CVPixelBufferRef)renderPixelBuffer:(CVPixelBufferRef)pixelBuffer withFrameId:(int)frameid items:(int*)items itemCount:(int)itemCount flipx:(BOOL)flip;
```

该函数中第三个参数 `items:(int*)items` 中的 `int *` 既可以表示 C 语言中的数组，又可以表示 OC 中的 int 型的内存地址，Demo 中是传一个 C 的 int 数组本身，然而在 Swift 里面 `int *` 会被认为是 int 型的内存地址。但是如果我传入 Int32 数组，会报以下错误（编译器认为该参数是一个 int 型的内存地址）：

```
Cannot convert value of type '[Int32]' to expected argument type 'UnsafeMutablePointer<Int32>!'
```

利益相关，正在测试集成贵司的 sdk 做动态贴纸，望尽快回复，谢谢。

**Comment by iTofu** [comment]
@jdbbjd

**Comment by jdbbjd** [comment]
UnsafeMutablePointer<Int32>(mutating: items)!
你可以这样使用试试

**Comment by iTofu** [comment]
谢谢，已通过传入 `&items` （`var items: [CInt] = [0, 0, 0]`）解决。

**Comment by jdbbjd** [comment]
好的
