### ISSUE TITLE
v7.0.0 pod install 失败

### ISSUE THREAD

**Issue by ytzeling** [Faceunity/FULiveDemo#53]
![Screenshot 2020-07-07 at 4 15 06 PM](https://user-images.githubusercontent.com/22390736/86745669-17b61a80-c06d-11ea-8f5c-7389c08dd052.png)

如图

**Comment by ElfSundae** [comment]
下载库失败 https://www.faceunity.com/sdk/FaceUnity-SDK-iOS-v7.0.0-lite.zip
重试，再不行就手动下载放到 CocoaPods 缓存目录。

**Comment by ytzeling** [comment]
重试成功，谢谢您
