### ISSUE TITLE
fuGetSystemError = 1 是什么意思？

### ISSUE THREAD

**Issue by ytzeling** [Faceunity/FULiveDemo#55]
自从升级了7.0后，renderPixel 老是获得 fuGetSystemError = 1，
可是这回调是空的， fuGetSystemErrorString(fuGetSystemError()) = ""

如果1 是有意义的话, NAMA_ERROR_SEED_RNG_FAILURE (failed to seed the RNG) 又是指什么呢？请给个方案处理。

**Comment by kurtchen1988** [comment]
证书的鉴权有问题，可联系我方商务处理。
