### ISSUE TITLE
你好，`didOutputVideoSampleBuffer:` 貌似没有回调 audio？

### ISSUE THREAD

**Issue by iTofu** [Faceunity/FULiveDemo#6]
RT，尝试对 sampleBuffer 保存到相册，播放时候没有音频？如果确实没有的话那只能再写一个 AudioRecord 了...

**Comment by iTofu** [comment]
@jdbbjd

**Comment by jdbbjd** [comment]
你好，我们的demo只是对图像的处理，故没有加入声音的录制，您可以已参考github中其他与录音录像的有关的开源项目实现录音功能
